### ISSUE TITLE
Unresponsive Layout after deleting a to-do task

### ISSUE THREAD

**Issue by itank-z** [achintyachaudhary/ctrlH#1]
<br> tag isn't deleted when i deleted to-do task and when i refresh page then it gets rendered properly.

Suggestion -
Make a change in code when you are deleting to-do delete that <br> tag also.

**Comment by achintyachaudhary** [comment]
OK thanks I'll look into that,

**Comment by achintyachaudhary** [comment]
Changed the layout of lists.
